### ISSUE TITLE
Work with release

### ISSUE THREAD

**Issue by MartynovIvan** [vaisakhsasikumar/my-electron-app#67]

**Comment by MartynovIvan** [comment]
you can trigger a GitHub Actions workflow (or pipeline) from another workflow using the `repository_dispatch` event. This way, you can even pass parameters from one workflow to another. Here’s a general overview of how you can achieve this:

### Step 1: Setup the Triggering Workflow

You need a workflow that uses the `repository_dispatch` event to trigger another workflow. This can be done using a GitHub Action that makes an API call to trigger the `repository_dispatch` event. Here's an example using `curl`:

```yaml
name: Trigger Another Workflow

on:
  workflow_dispatch:
    inputs:
      example-param:
        description: 'An example parameter'
        required: true

jobs:
  trigger:
    runs-on: ubuntu-latest
    steps:
      - name: Trigger another workflow via repository_dispatch
        run: |
          curl -X POST \
            -H "Accept: application/vnd.github.v3+json" \
            -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
            https://api.github.com/repos/<owner>/<repo>/dispatches \
            -d '{"event_type": "custom_event", "client_payload": {"example-param": "${{ github.event.inputs.example-param }}"}}'
```

### Step 2: Setup the Target Workflow

Create another workflow file that will be triggered by the `repository_dispatch` event:

```yaml
name: Target Workflow

on:
  repository_dispatch:
    types: [custom_event]

jobs:
  target:
    runs-on: ubuntu-latest
    steps:
      - name: Run something with the parameter
        run: echo "Parameter passed: ${{ github.event.client_payload.example-param }}"
```

### Explanation

1. **Triggering Workflow**: You make a POST request to the GitHub API's `/dispatches` endpoint with the `repository_dispatch` event type and include any parameters in the `client_payload`.

2. **Target Workflow**: Listens for a specific `repository_dispatch` event type. It then has access to any parameters passed in the `client_payload`, which you can use within the steps of that workflow.

### Notes

- **Permissions**: Ensure that the GitHub token used has sufficient permissions to trigger `repository_dispatch`. The default `GITHUB_TOKEN` should have these permissions, but you may need to adjust repository settings or use a Personal Access Token for cross-repo workflows.

- **Security**: Be cautious with sensitive data. Ensure tokens and sensitive data are stored in GitHub secrets, not directly in the workflow files.

- **Event Type**: You can define any string for the `event_type`; ensure it matches between the triggering and target workflows.

This setup allows for flexible CI/CD pipelines where you can string together complex workflows across projects or repositories.
